version: "3"
services:
  twmmongodb:
    image: mongo:latest
    container_name: "twmmongodb"
    ports:
      - "27017:27017"
  springboot-mongodb:
    image: springboot-mongodb:6.0
    container_name: springboot-mongodb
    ports:
      - "8080:8080"
    links:
      - twmmongodb